# Generated by Django 4.0 on 2024-05-06 17:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_content', '0006_rename_desctiption_task_description'),
        ('user', '0002_alter_user_password'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTryOpenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'User try open question',
            },
        ),
        migrations.CreateModel(
            name='UserTryProgramTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.TextField()),
            ],
            options={
                'verbose_name': 'User try program task',
            },
        ),
        migrations.CreateModel(
            name='UserTryQuestionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceAnswer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=10)),
            ],
            options={
                'verbose_name': 'User try question task',
            },
        ),
        migrations.CreateModel(
            name='UserTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectId', models.PositiveIntegerField()),
                ('result', models.BooleanField(default=False)),
                ('contentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tasks', models.ManyToManyField(to='course_content.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'User try',
                'verbose_name_plural': 'User attempts',
            },
        ),
    ]
