# Generated by Django 4.0 on 2024-05-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_lesson', '0002_remove_usertry_tasks_usertry_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
