# Generated by Django 4.0 on 2024-05-05 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_remove_course_isactive_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(db_table='StundetsCourse', related_name='stundets_course', to=settings.AUTH_USER_MODEL),
        ),
    ]
