# Generated by Django 4.0 on 2024-01-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_refreshuser_refresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshuser',
            name='refresh',
            field=models.TextField(),
        ),
    ]
