# Generated by Django 4.0 on 2024-01-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_refreshuser_refresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshuser',
            name='exp',
            field=models.DateField(null=True),
        ),
    ]
