# Generated by Django 4.0 on 2024-02-18 14:45

import autoslug.fields
import course.genarationSlug
import course_content.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rigthText', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Open question',
                'verbose_name_plural': 'Open questions',
            },
        ),
        migrations.CreateModel(
            name='ProgramTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testFile', models.FileField(upload_to=course_content.models.courseProgramFilePath)),
            ],
            options={
                'verbose_name': 'Program task',
                'verbose_name_plural': 'Program tasks',
            },
        ),
        migrations.CreateModel(
            name='QuestionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceQuestions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=10)),
                ('choiceRight', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=10)),
            ],
            options={
                'verbose_name': 'Question task',
                'verbose_name_plural': 'Question tasks',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('serialNumber', models.PositiveSmallIntegerField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=course.genarationSlug.genarationSlug, unique=True)),
                ('idCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='TopicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=course.genarationSlug.genarationSlug, unique=True)),
            ],
            options={
                'verbose_name': 'Topic info',
                'verbose_name_plural': 'Topics info',
            },
        ),
        migrations.CreateModel(
            name='TopicNavigate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.PositiveSmallIntegerField()),
                ('objectId', models.PositiveIntegerField()),
                ('contentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('idTopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_content.topic')),
            ],
            options={
                'verbose_name': 'Topic navigate',
                'verbose_name_plural': 'Topics navigate',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desctiption', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('objectId', models.PositiveIntegerField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=course.genarationSlug.genarationSlug, unique=True)),
                ('contentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
