# Generated by Django 4.0 on 2024-02-25 17:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='desctiption',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None),
        ),
        migrations.AlterField(
            model_name='topicinfo',
            name='text',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None),
        ),
    ]
