# Generated by Django 4.0 on 2024-04-27 13:25

import course_content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_content', '0003_alter_task_desctiption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicinfo',
            name='text',
            field=models.FileField(upload_to=course_content.models.courseTextInfoFilePath),
        ),
    ]
