# Generated by Django 4.0 on 2024-04-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_content', '0005_programtask_programlanguage_alter_task_desctiption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='desctiption',
            new_name='description',
        ),
    ]
